name: Leapyear Tests

on:
  push

jobs:
  test:
    runs-on: windows-latest


  env:
    MODE: "dev"

  steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Leapyear test
      run: pytest ./test_isleapyear.py